In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/auction_data_cleaned.csv', index_col=0)
df.head()

,artist_name,title,date,medium,dims,auction_date,auction_house,auction_sale,auction_lot,price_realized,...,auction_year,price_realized_USD_constant_2022,area_cm_sq,volume_cm_cu,living,years_after_death_of_auction,artist_age_at_auction,artist_age_at_artwork_completion,artwork_age_at_auction,years_ago_of_auction
0,Pablo Picasso,Fillette au bateau (Maya),1938,oil on canvas,73.3 x 60 cm,"Mar 1, 2023",Sotheby's• London,Modern & Contemporary Evening Auction,Lot6002,NaN,...,2023,NaN,4398.00,NaN,0,50.0,NaN,57.0,85.0,0
1,Pablo Picasso,Homme assis,1969,oil on panel laid down on cradled panel,28.7 x 56.6 cm,"Nov 30, 2022",Christie's,Live Auction 19901 20th/21st Century Art Eveni...,Lot35,"HK\$10,650,000• US\$1,363,489",...,2022,1363489.0,1624.42,NaN,0,49.0,NaN,88.0,53.0,1
2,Pablo Picasso,Buffalo Bill,1911,oil and sand on canvas,33.3 x 46.3 cm,"Nov 17, 2022",Christie's,Live Auction 20988 20th Century Evening Sale,Lot12,"US\$12,412,500",...,2022,12412500.0,1541.79,NaN,0,49.0,NaN,30.0,111.0,1
3,Pablo Picasso,Homme à la moustache,1970,oil and oil stick on panel,65.1 x 129.4 cm,"Nov 17, 2022",Christie's,Live Auction 20988 20th Century Evening Sale,Lot30,"US\$4,620,000",...,2022,4620000.0,8423.94,NaN,0,49.0,NaN,89.0,52.0,1
4,Pablo Picasso,Le peintre et son modèle,1964,oil and ripolin on canvas,195.0 x 130.0 cm,"Nov 17, 2022",Christie's,Live Auction 20988 20th Century Evening Sale,Lot36,"US\$10,351,500",...,2022,10351500.0,25350.00,NaN,0,49.0,NaN,83.0,58.0,1

In [3]:
print("This dataset conains {:,} auction records.".format(len(df)))
print("It includes auction data for {} artists from {} to {}".
      format(len(df['artist_name'].unique()), df['auction_year'].min(), df['auction_year'].max()))
print("Of these, {:,} auctions resulted in valid sales".format(df['price_realized_USD'].notna().sum()))

This dataset conains 53,034 auction records.
It includes auction data for 141 artists from 1986 to 2023
Of these, 40,798 auctions resulted in valid sales